apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
spec:
  selector:
   {{- include "labels" .| indent 4 }}
  ports:
    - protocol: {{ .Values.ports.protocol }}
      port: {{ .Values.ports.port }}
      targetPort: {{ .Values.ports.targetPort }}
